pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
  displayName: 'Install Python'
- script: |
    python -m venv env
    source env/bin/activate
    pip install -r requirements.txt
  displayName: 'Install dependencies'
- script: |
    source env/bin/activate
    pytest --junitxml=junit/test-results.xml --cov=app --cov-report=xml
  displayName: 'Run unit tests'
  
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage.xml'
  displayName: 'Publish code coverage results'

